version = 5.3.1
archive_dir = /etc/letsencrypt/archive/npm-1
cert = /etc/letsencrypt/live/npm-1/cert.pem
privkey = /etc/letsencrypt/live/npm-1/privkey.pem
chain = /etc/letsencrypt/live/npm-1/chain.pem
fullchain = /etc/letsencrypt/live/npm-1/fullchain.pem
[renewalparams]
account = f0fcafa20fb765b0c8fc7583f69ee6aa
key_type = ecdsa
elliptic_curve = secp384r1
preferred_chain = ISRG Root X1
pref_challs = http-01,
config_dir = /etc/letsencrypt
work_dir = /tmp/letsencrypt-lib
logs_dir = /data/logs
authenticator = webroot
webroot_path = /data/letsencrypt-acme-challenge,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
syncora.cyou = /data/letsencrypt-acme-challenge
[acme_renewal_info]
ari_retry_after = 2026-06-12T15:30:52
